version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:ro
      - ./mosquitto/data/:/mosquitto/data:rw
      - ./mosquitto/log/:/mosquitto/log/:rw

  db:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data:rw
