services:
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:ro
      - ./mosquitto/data/:/mosquitto/data:rw
      - ./mosquitto/log/:/mosquitto/log/:rw
