version: "3.9"

services:
  mqtt:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:ro
      - ./mosquitto/data/:/mosquitto/data:rw
      - ./mosquitto/log/:/mosquitto/log/:rw

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=airnoise
      - MYSQL_USER=airnoise
      - MYSQL_PASSWORD=airnoise
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql:rw
