# Generated by Django 4.1.5 on 2023-01-05 22:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_24bit_hex', models.CharField(max_length=16)),
                ('flight_name', models.CharField(blank=True, max_length=32)),
                ('squawk_code', models.CharField(blank=True, max_length=16)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('rms', models.IntegerField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.PositiveIntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='monitor.flight')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.location')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.location'),
        ),
        migrations.CreateModel(
            name='AudioBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('data', models.BinaryField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.location')),
            ],
        ),
    ]
