# Generated by Django 4.1.5 on 2023-01-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="squawk_code",
        ),
        migrations.RemoveField(
            model_name="flightdata",
            name="location",
        ),
        migrations.AddField(
            model_name="flightdata",
            name="squawk_code",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
